-- ============================================================================
-- Migration: Fix items.trials_status database drift
--
-- Root cause:
--   backend/src/main/resources/schema.sql defines trials_status as VARCHAR(30),
--   which is the correct, intended type (Item.trialsStatus is mapped with
--   @Enumerated(EnumType.STRING), which only ever needs a VARCHAR column).
--
--   The live database, however, currently has trials_status as a native MySQL
--   ENUM('PENDING','IN_PROGRESS','COMPLETED','ON_HOLD') — created manually at
--   some point outside the codebase, and missing the 'TESTING' value that
--   Item.TrialsStatus (Java) has included since it was added. Hibernate
--   ddl-auto=update never touches this because VARCHAR -> ENUM conversions
--   are never generated by Hibernate; only the reverse direction is needed
--   here, converting the stray ENUM back to VARCHAR(30) to match schema.sql.
--
-- This migration is safe: converting ENUM -> VARCHAR(30) preserves all
-- existing values as their string representation. No data is lost.
-- ============================================================================

ALTER TABLE items
    MODIFY COLUMN trials_status VARCHAR(30) DEFAULT NULL;

-- ============================================================================
-- Verify:
--   SHOW COLUMNS FROM items LIKE 'trials_status';
-- Expected: Type = varchar(30)
-- ============================================================================